# ============================================================
#  Nofilter Lab - Shopify setup (Windows / PowerShell)
#
#  Run this once to connect your site to your Shopify store.
#  It asks you 3 questions and writes shopify-config.js for you,
#  so you never have to edit code by hand.
#
#  HOW TO RUN:
#    1. Open PowerShell in this project folder.
#    2. Type:   .\setup.ps1     and press Enter.
#  (If Windows blocks it, first run:
#     Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass )
# ============================================================

$ErrorActionPreference = 'Stop'
$configPath = Join-Path $PSScriptRoot 'shopify-config.js'

function Write-Title($text) {
    Write-Host ''
    Write-Host $text -ForegroundColor Cyan
    Write-Host ('-' * $text.Length) -ForegroundColor DarkGray
}

function Read-Required($prompt) {
    while ($true) {
        $value = (Read-Host $prompt).Trim()
        if ($value) { return $value }
        Write-Host "  That can't be empty - please paste the value." -ForegroundColor Yellow
    }
}

Write-Title 'Connect your site to Shopify'
Write-Host "You'll paste 3 values from your Shopify admin. Not sure where to find"
Write-Host "them? Open guide.html in your browser first - it shows every click."

# --- 1. Store domain ---------------------------------------------------------
Write-Title '1 of 3  -  Store domain'
Write-Host 'The address ending in .myshopify.com (e.g. my-cool-shop.myshopify.com).'
$domain = Read-Required 'Store domain'
# Tidy up common paste mistakes: strip protocol, any path, trailing slash.
$domain = $domain -replace '^https?://', ''
$domain = ($domain -split '/')[0]
$domain = $domain.Trim().TrimEnd('/')
if ($domain -notmatch '\.myshopify\.com$') {
    Write-Host "  Heads up: that doesn't end in .myshopify.com. That's fine if you're" -ForegroundColor Yellow
    Write-Host "  using a custom domain, but double-check it's your store's address." -ForegroundColor Yellow
}

# --- 2. Storefront access token ---------------------------------------------
Write-Title '2 of 3  -  Storefront API access token'
Write-Host 'The long string from your app''s "API credentials" tab.'
Write-Host 'This is the STOREFRONT token - NOT an admin key (those start with shpat_).'
$token = Read-Required 'Storefront access token'
if ($token -like 'shpat_*') {
    Write-Host "  Warning: that looks like an ADMIN API key, not a Storefront token." -ForegroundColor Yellow
    Write-Host "  Re-check Step 3 in the guide - you want the Storefront API token." -ForegroundColor Yellow
}

# --- 3. Product handle -------------------------------------------------------
Write-Title '3 of 3  -  Product handle'
Write-Host 'The part of your product''s URL after /products/ (e.g. the-clear).'
Write-Host 'You can paste the whole product URL and this will pull the handle out.'
$handle = Read-Required 'Product handle (or full product URL)'
if ($handle -match '/products/([^/?#]+)') {
    $handle = $Matches[1]   # pulled the handle out of a pasted URL
}
$handle = $handle.Trim().Trim('/')

# --- Sanity check: reject stray double-quotes that would break the JS file ---
foreach ($pair in @(@('Store domain', $domain), @('Access token', $token), @('Product handle', $handle))) {
    if ($pair[1] -match '"') {
        Write-Host ''
        Write-Host "$($pair[0]) contains a double-quote character, which isn't valid. Please re-run and paste it without quotes." -ForegroundColor Red
        exit 1
    }
}

# --- Confirm before writing --------------------------------------------------
Write-Title 'Please confirm'
Write-Host "  Store domain     : $domain"
Write-Host "  Storefront token : $($token.Substring(0, [Math]::Min(6, $token.Length)))... (hidden)"
Write-Host "  Product handle   : $handle"
Write-Host ''
if (Test-Path $configPath) {
    Write-Host 'This will overwrite your existing shopify-config.js.' -ForegroundColor Yellow
}
$ok = (Read-Host 'Write these to shopify-config.js? (y/n)').Trim().ToLower()
if ($ok -ne 'y') {
    Write-Host 'Cancelled - nothing was changed.' -ForegroundColor DarkGray
    exit 0
}

# --- Write the config file ---------------------------------------------------
$content = @"
// ============================================================
// SHOPIFY SETUP - generated by setup.ps1
// Re-run setup.ps1 to change these, or edit the values by hand.
// ============================================================
const shopifyConfig = {
  // Your store's domain, exactly as Shopify shows it.
  storeDomain: "$domain",

  // Your Storefront API access token (NOT your admin API key).
  storefrontAccessToken: "$token",

  // The "handle" of the product you want to sell - the part of its
  // URL after /products/.
  productHandle: "$handle",
};

export default shopifyConfig;
"@

Set-Content -Path $configPath -Value $content -Encoding utf8

Write-Host ''
Write-Host 'Done! shopify-config.js is connected to your store.' -ForegroundColor Green
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host '  npm install     (first time only - downloads what the site needs)'
Write-Host '  npm run dev     (starts your site at http://localhost:3000)'
Write-Host ''
Write-Host 'Then open http://localhost:3000, add the product to your bag, and click'
Write-Host 'Check out - it should take you to your Shopify checkout page.'
